### ISSUE TITLE
Cannot stream to channel

### ISSUE THREAD

**Issue by talhazan** [AsmSafone/VideoPlayerBot#10]
When sending /stream command in PM it does not respond, the /stream command cannot be sent through the channel, but should be sent through PM when sending through the channel the bot response with an icon (auth issue?)

When engaging through the group it works fine.

I'm using /stream of youtube live stream.

**Comment by Achu2234** [comment]
you want to put your channel oid in CHAT_ID Var in railway or herku

**Comment by Achu2234** [comment]
@AsmSafone colse this issue

**Comment by AsmSafone** [comment]
> When sending /stream command in PM it does not respond, the /stream command cannot be sent through the channel, but should be sent through PM when sending through the channel the bot response with an icon (auth issue?)
> 
> When engaging through the group it works fine.
> 
> I'm using /stream of youtube live stream.
[In reply to Aurax]
channel stream has removed as of multiple grp support update 🥲 if channel then it can't be used in multi chat. Btw soon update alpha branch with channel support again. Stay tuned. In the mean time u can try this [fork](https://github.com/S1-BOTS/VideoPlayerBot)
