### ISSUE TITLE
Remove the alpha branch.

### ISSUE THREAD

**Issue by subinps** [AsmSafone/VideoPlayerBot#17]
Hey Developer.
I was unaware of this alpha branch in your repository. Was watching you main branch till today. Unexpectedly found something on alpha branch.
Have you ever care about the true owner of the code that you used there?

Have you changed anything other than some strings ?
You just cloned my [ repository ](https://github.com/subinps/VCPlayerBot) without any  'ulupp'.

A [note](https://github.com/subinps/VCPlayerBot#note) was clearly mentioned in the repository, have you ever read that? . To be precise the note was clearly targeted for this.

have you ever been respect the [LICENCE](https://github.com/subinps/VCPlayerBot/blob/main/LICENSE) in the repo?

I request you to delete the alpha branch and if you want to modify the code of  [ VCPlayerBot ](https://github.com/subinps/VCPlayerBot) and release , you can always fork the repo and do the same.

Rising this issue here because when the same was asked in your [Support Group](https://telegram.dog/safothebot), You just deleted the post.

**Comment by AsmSafone** [comment]
Have you checked [credit section](https://github.com/AsmSafone/VideoPlayerBot/tree/alpha#credits) ?
Btw this branch is only for my grp! I have added functions as i need to run on my grp vc.

**Comment by subinps** [comment]
> Have you checked [credit section](https://github.com/AsmSafone/VideoPlayerBot/tree/alpha#credits) ?
> Btw this branch is only for my grp! I have added functions as i need to run on my grp vc.

Yes you added the credits, but it wont make sense for me . 
you may please  fork the repo and make changes .
Its a request.
