### ISSUE TITLE
Ability to play new sent /stream without need to /endstream 

### ISSUE THREAD

**Issue by ravana69** [AsmSafone/VideoPlayerBot#3]

**Comment by AsmSafone** [comment]
Ok. Soon!!

**Comment by sattttya** [comment]
https://github.com/AsmSafone/VideoPlayerBot/commit/e0ace38f29614ce229e67589cabc02b58ab78fa1

**Comment by AsmSafone** [comment]
Done: https://github.com/AsmSafone/VideoPlayerBot/commit/b89fd212abb1b6a735c46d37f74a17ec651f3592
