### ISSUE TITLE
Not deploy

### ISSUE THREAD

**Issue by devilroogan** [AsmSafone/VideoPlayerBot#30]
Running command git clone -q https://github.com/pyrogram/pyrogram /tmp/pip-req-build-nouvykbx
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/pyrogram/pyrogram /tmp/pip-req-build-nouvykbx
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
The command '/bin/sh -c pip3 install -U -r requirements.txt' returned a non-zero code: 1

**Comment by Achu2234** [comment]
Fixed now you can make
