### ISSUE TITLE
Why Deleted Alpha

### ISSUE THREAD

**Issue by SanuCoder** [AsmSafone/VideoPlayerBot#36]
Alpha is very usefull why deleted it 😣
Sed

**Comment by munnadaniels** [comment]
> just moved [here](https://github.com/S1-BOTS/VideoPlayerBot)

Send Me That Alpha Repo bro🤧

**Comment by AsmSafone** [comment]
> > just moved [here](https://github.com/S1-BOTS/VideoPlayerBot)
> 
> Send Me That Alpha Repo bro🤧

https://github.com/S1-BOTS/VideoPlayerBot
