### ISSUE TITLE
pause command

### ISSUE THREAD

**Issue by Maaxxie1227** [AsmSafone/VideoPlayerBot#4]
can u guys pls add a pause command for stream videos? it'll be so much wonderful

**Comment by AsmSafone** [comment]
Ok. will try!

**Comment by bryanseth** [comment]
May I know, when i import from this depo to my github...
if this repo have update, is it my one also will auto update?

or i need to self update as well?

**Comment by satttyaendraa** [comment]
Use fetch Upstream repo at top of your forked repo

**Comment by AsmSafone** [comment]
> can u guys pls add a pause command for stream videos? it'll be so much wonderful

Done! https://github.com/AsmSafone/VideoPlayerBot/commit/b737334bb7e8eadb28d926543fe6d6b19459ebee
